services:
  db:
    image: postgres:15-alpine
    command: -c fsync=off -c full_page_writes=off
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - sites_postgres_data:/var/lib/postgresql/data

volumes:
  sites_postgres_data:
    driver: local
