name: Build Pipeline

on:
  pull_request:
    branches: ["**"]
  push:
    branches:
      - test
      - stage
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependencies
        run: |
          npm ci
          cd analytics && npm ci && cd ..
      - name: Lint & Audit
        run: |
          npm run lint && npm audit
          cd analytics
          npm run lint && npm audit
          cd ..

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      nats:
        image: nats:latest
        ports:
          - '4222:4222'
      redis:
        image: redis/redis-stack:7.0.6-RC9
        ports:
          - 6379:6379
          - 8001:8001
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependencies
        run: |
          npm ci
          cd analytics && npm ci && cd ..
      - name: Setup Environment
        run: cp .env.example .env && source .env && cp .env.example analytics/.env && source analytics/.env
      - name: Run Migrations
        run: npm run migrate
      - name: Run Tests
        run: |
          NODE_OPTIONS="--max-old-space-size=4096" npm run test
          npm run test:e2e
          cd analytics
          npm run test
          npm run test:e2e
          cd ..
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/**
            analytics/coverage/**

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build URL Shortener Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.app
          push: false
          tags: url-shortener:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build Analytics Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.analytics
          push: false
          tags: url-shortener-analytics:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependencies
        run: |
          npm ci
          cd analytics && npm ci && cd ..
      - name: Build Applications
        run: |
          npm run build
          cd analytics && npm run build && cd ..
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/**
            analytics/dist/**
